Bilietai/Models/Administrator.cs
/**
 * @(#) Administrator.cs
 */

public class Administrator : User
{
}

Bilietai/Models/Movie.cs
/**
 * @(#) Movie.cs
 */

public class Movie
{
	string title;	
	string description;	
	double length;	
	string genre;	
	int year;
	double rating;	
    
	Ticket ticket;
	
	Showing showing;
	
	public void insert(  )
	{
		
	}
	
	public void select(  )
	{
		
	}
	
	public void update(  )
	{
		
	}
	
	public void delete(  )
	{
		
	}
	
}

Bilietai/Models/Order.cs
/**
 * @(#) Order.cs
 */

public class Order
{
	double full_price;
	
	User user;
	
	Ticket ticket;
	
	Payment payment;
	
	public void insert(  )
	{
		
	}
	
	public void update(  )
	{
		
	}
	
	public void delete(  )
	{
		
	}
	
}

Bilietai/Models/Payment.cs
/**
 * @(#) Payment.cs
 */

public class Payment
{
	string bank;
	
	float account_number;
	
	string payment_type;
	
	Order order;
	
	public void insert(  )
	{
		
	}
	
	public void select(  )
	{
		
	}
	
	public void update(  )
	{
		
	}
	
}

Bilietai/Models/Seat.cs
/**
 * @(#) Seat.cs
 */

public class Seat
{
	int row;
	
	int seat;
	
	Showing showing;
	
	Theatre theatre;
	
	Ticket ticket;
	
	public void update(  )
	{
		
	}
	
	public void select(  )
	{
		
	}
	
}

Bilietai/Models/Showing.cs
/**
 * @(#) Showing.cs
 */
using System;

public class Showing
{
	DateTime time;
	
	Movie movie;
	
	Seat seat;
	
	Ticket ticket;
	
}

Bilietai/Models/Theatre.cs
/**
 * @(#) Theatre.cs
 */

public class Theatre
{
	int seats_total;
	
	int empty_seats;
	
	bool free;
	
	int number;
	
	Ticket ticket;
	
	Seat seat;
	
	public void update(  )
	{
		
	}
	
}

Bilietai/Models/Ticket.cs
using System;
/**
* @(#) Ticket.cs
*/
public class Ticket
{
	double price;
	
	DateTime start_time;
	
	int seat_number;
	
	float barcode;
	
	Movie movie;
	
	Theatre theatre;
	
	Order order;
	
	Showing showing;
	
	Seat seat;

	public void select(  )
	{
		
	}
	
	public void delete(  )
	{
		
	}
	
	public void insert(  )
	{
		
	}
	
}

Bilietai/Models/User.cs
/**
 * @(#) User.cs
 */

public class User
{
	String login;
	
	String password;
	
	String email;
	
	String firstName;
	
	String lastName;
	
	User_state state;
	
	Order order;
	
	public void select(  )
	{
		
	}
	
	public void delete(  )
	{
		
	}
	
	public void insert(  )
	{
		
	}
	
}

Bilietai/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bilietai.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Tickets()
        {
            return View();
        }
    }
}

Bilietai/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bilietai.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Movie()
        {
            return View();
        }
        public ActionResult MoviePage()
        {
            return View();
        }
    }
}

Bilietai/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;

namespace Bilietai.Controllers
{
    public class TicketController : Controller
    {
        // GET: Ticket
        public ActionResult Ticket()
        {
            return View();
        }

        [HttpPost]
        public ActionResult generateTicket()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                
                string checkedValues = Request.Form["checkedValues"];
                DateTime fileCreationDatetime = DateTime.Now;
                string data = fileCreationDatetime.ToString(@"yyyy-MM-dd") + " " + fileCreationDatetime.ToString(@"HH:mm:ss");
                Rectangle envelope = new Rectangle(600, 200);
                Document doc = new Document(envelope, 20f, 10f, 30f, 20f);
                Font verdana = FontFactory.GetFont("Verdana", 14, Font.BOLD);
                PdfWriter writer = PdfWriter.GetInstance(doc, ms);
                doc.Open();
                Image logo = Image.GetInstance(Server.MapPath("~/images/logo.jpg"));
                logo.SetAbsolutePosition(480, 120);
                logo.ScalePercent(10f);
                doc.Add(logo);
                doc.Add(new Paragraph(data, verdana));
                doc.Add(new Paragraph("Movie: ", verdana));
                doc.Add(new Paragraph("Seat: " + checkedValues, verdana));
                doc.Add(new Paragraph("Price: ", verdana));
                doc.Close();
                byte[] bytes = ms.ToArray();
                ms.Close();

                return File(bytes, "application/pdf", "Ticket.pdf");
            }
        }
    }
}

Bilietai/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Bilietai/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Bilietai/Views/Movie/Movie.cshtml
@{
    ViewBag.Title = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>
<div class="container" style="margin-top:50px;">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="col-item">
                <div class="post-img-content">
                   <img src="../images/deadpool.jpg" class="img-responsive" />
                </div>
                <div class="info">
                    <div class="row">
                        <div class="price col-md-6">
                            <h5>DeadPool 2</h5>
                            <h5 class="price-text-color">5.99€</h5>
                        </div>
                    </div>
                    <div class="separator clear-left">
                        <p class="btn-add">
                            <i class="fa fa-shopping-cart"></i><a href="#" class="hidden-sm">Buy ticket</a>
                        </p>
                        <p class="btn-details">
                            <i class="fa fa-list"></i>@Html.ActionLink("More details", "MoviePage", "Movie")
                        </p>
                    </div>
                    <div class="clearfix">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--<center>
<table style="width: 10%;" border="0" cellpadding="20">
    <tbody>
        <tr>
            <td><b></b></td>
            <td><b>1</b></td>
            <td><b>2</b></td>
            <td><b>3</b></td>
            <td><b>4</b></td>
            <td><b>5</b></td>
            <td><b>6</b></td>
            <td><b>7</b></td>
            <td><b>8</b></td>
            <td><b>9</b></td>
            <td><b>10</b></td>
            <td><b>11</b></td>
            <td><b>12</b></td>
        </tr>
        <tr>
            <td><b>A</b></td>
            <td><input type="checkbox" name="checkedValues" value="A1" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A2" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A3" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A4" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A5" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A6" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A7" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A8" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A9" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A10" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A11" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="A12" /><span></span></td>
        </tr>
        <tr>
            <td><b>B</b></td>
            <td><input type="checkbox" name="checkedValues" value="B1" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B2" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B3" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B4" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B5" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B6" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B7" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B8" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B9" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B10" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B11" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="B12" /><span></span></td>
        </tr>
        <tr>
            <td><b>C</b></td>
            <td><input type="checkbox" name="checkedValues" value="C1" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C2" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C3" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C4" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C5" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C6" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C7" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C8" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C9" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C10" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C11" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="C12" /><span></span></td>
        </tr>
        <tr>
            <td><b>D</b></td>
            <td><input type="checkbox" name="checkedValues" value="D1" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D2" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D3" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D4" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D5" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D6" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D7" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D8" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D9" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D10" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D11" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="D12" /><span></span></td>
        </tr>
        <tr>
            <td><b>E</b></td>
            <td><input type="checkbox" name="checkedValues" value="E1" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E2" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E3" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E4" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E5" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E6" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E7" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E8" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E9" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E10" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E11" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="E12" /><span></span></td>
        </tr>
        <tr>
            <td><b>F</b></td>
            <td><input type="checkbox" name="checkedValues" value="F1" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F2" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F3" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F4" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F5" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F6" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F7" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F8" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F9" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F10" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F11" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="F12" /><span></span></td>
        </tr>
        <tr>
            <td><b>G</b></td>
            <td><input type="checkbox" name="checkedValues" value="G1" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G2" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G3" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G4" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G5" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G6" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G7" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G8" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G9" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G10" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G11" /><span></span></td>
            <td><input type="checkbox" name="checkedValues" value="G12" /><span></span></td>
        </tr>
    </tbody>
</table>
</center>
    ---->

Bilietai/Views/Movie/MoviePage.cshtml
@{
    ViewBag.Title = "MoviePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MoviePage</h2>

Bilietai/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Kino bilietų rezervavimo sistema</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Kino bilietų rezervavimo sistema", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Movies", "Movie", "Movie")</li>
                    <li>@Html.ActionLink("Ticket", "Ticket", "Ticket")</li
>                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Kino bilietų rezervavimo sistema</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Bilietai/Views/Ticket/Ticket.cshtml
@{
    ViewBag.Title = "Tickets";
}    
<h2>@ViewBag.Title</h2>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@using (Html.BeginForm("generateTicket", "Ticket", FormMethod.Post))
{
    <center><button type="submit" value="Generate ticket" style="font-size:12px">Generate ticket       
      <i class="fa fa-file-pdf-o"></i></button></center>
}